version: "3.9"

services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /etc/localtime:/etc/localtime:ro 
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.52.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - cadvisor

  grafana:
    image: grafana/grafana:10.2.3
    container_name: grafana
    ports:
      - "3005:3000"
    volumes:
      - ./monitoring/grafana:/var/lib/grafana
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - prometheus
