version: '3.8'

services:
  auth:
    build: ./auth
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production

  products:
    build: ./products
    ports:
      - "3003:3000"
    environment:
      - NODE_ENV=production

  gateway:
    build: ./gateway
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
