services:
  gateway:
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - ./gateway/.env.production
    depends_on:
      - auth
      - products
    networks:
      - micro_net

  auth:
    build:
      context: .
      dockerfile: ./auth/Dockerfile
    env_file:
      - ./auth/.env.production
    expose:
      - "8085"
    networks:
      - micro_net

  products:
    build:
      context: .
      dockerfile: ./products/Dockerfile
    env_file:
      - ./products/.env.production
    expose:
      - "8083"
    networks:
      - micro_net

networks:
  micro_net:
    driver: bridge
