
services:
  gateway:
    build: ./gateway
    ports:
      - "4000:4000"  # Exponemos solo el gateway
    depends_on:
      - auth
      - products
    networks:
      - micro-net

  auth:
    build: ./auth
    expose:
      - "8085"  # No se expone a host, pero accesible por los otros servicios
    networks:
      - micro-net

  products:
    build: ./products
    expose:
      - "8083"
    networks:
      - micro-net

networks:
  micro-net:
    driver: bridge
