FROM node:20-alpine

RUN apk add --no-cache bash

WORKDIR /app

COPY gateway/package*.json ./gateway/
COPY common/package*.json ./common/

RUN npm install --prefix ./common
RUN npm install --prefix ./gateway

COPY common ./common
COPY gateway ./gateway

RUN npm run build --prefix ./common

WORKDIR /app/gateway

CMD ["npm", "run", "dev"]
