FROM node:20-alpine

RUN apk add --no-cache bash

WORKDIR /app

COPY products/package*.json ./products/
COPY common/package*.json ./common/

RUN npm install --prefix ./common
RUN npm install --prefix ./products

COPY common ./common
COPY products ./products

RUN npm run build --prefix ./common

WORKDIR /app/products

CMD ["npm", "run", "dev"]
